python bench.py --model hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4 --D 1
python bench.py --model hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4 --D 2
python bench.py --model hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4 --D 4
python bench.py --model hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4 --D 8
python bench.py --model hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4 --D 16
python bench.py --model hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4 --D 32
python bench.py --model hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4 --D 48
python bench.py --model hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4 --D 64
python bench.py --model hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4 --D 80
python bench.py --model hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4 --D 96
python bench.py --model hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4 --D 128